### ISSUE TITLE
Displayed role ratings are inconsistent.

### ISSUE THREAD

**Issue by splintermind** [splintermind/Dwarf-Therapist#152]
Currently in most places (tooltips, detail dock, text cell drawing method) the raw role rating is displayed, while in other instances (other cell drawing methods) the adjusted display value is used instead (0-100 values).

Role comparisons between the raw values is arguably more difficult this way due to the smaller scale (eg. 55.1 vs 55.4 instead of 62 vs 73). It also renders the text cell drawing method useless, as it's rounded.

**Comment by thistleknot** [comment]
In theory, since the two sets of numbers are our "final" output (raw vs transformed from 0 to 100) the relationship that the role optimizer uses is maintained (> or < with other values); however, for visual comparison, when I mapped it out to a graph (the old 0 to 100% method outputted to csv), it looked far different than two spikes around 50%; which means the visual relationship isn't [as] maintained.  Plus the fact, that since most values are close to 50% anyways, it may push EVEN MORE values around 50% and possibly due to rounding at 2 decimal places is maybe why the histogram looks warped when it's on a scale of 0 to 100% vs raw.

The problem with the numbers being rounded isn't as big a deal when you think about it, because the sorting behaviour is still maintained.  One just has to look at the tooltip is it?  To get the proper #.

**Comment by splintermind** [comment]
The issue with displaying the raw values is that many (especially new) users, not knowing the underlying mechanics of how the role ratings are generated, will understandably consider ratings like 55.1 and 55.9 to be virtually equal ratings, when they're actually quite different.

The rounding issue is purely to do with drawing cell values with the text method. When using the raw ratings there's a lot less variation after rounding. The main inconsistency to note here is that every other drawing method uses the 0-100 values, except the text method.
