### ISSUE TITLE
Blurry fonts

### ISSUE THREAD

**Issue by CaviaPorcellus** [splintermind/Dwarf-Therapist#216]
The fonts in Dwarf-Therapist look fuzzy, as if subpixel rendering is somehow turned off (or some similar problem). I'm using Ubuntu 14.04. Thanks.

**Comment by CaviaPorcellus** [comment]
Forgot to add a screenshot:
![screenshot from 2014-11-12 00 10 13](https://cloud.githubusercontent.com/assets/5825551/5005666/051ad500-6a01-11e4-9b66-27f42c1b26d5.png)

**Comment by Hello71** [comment]
looks fine to me. afaik dt does nothing funny with text, so try asking #ubuntu or the forums about qt text rendering.

**Comment by CaviaPorcellus** [comment]
It's definitely messed up: the subpixel rendering of the text in DT is only in greyscale. Compare the text of DT in this zoomed-in screenshot to that of Gedit and the toolbars. But yeah, maybe it's a qt issue.
![screenshot from 2014-11-24 00 50 14](https://cloud.githubusercontent.com/assets/5825551/5161325/11530f3c-7374-11e4-9b49-1676653848b6.png)

**Comment by splintermind** [comment]
I encountered this today and had to modify the fonts.conf to enable/force rgb subpixel rendering. It was also on ubuntu 14.04, so that may have something to do with it.

[The 'subpixel rendering' section was all I needed to modify, but there are other adjustments that may improve things further](https://wiki.archlinux.org/index.php/font_configuration)

**Comment by CaviaPorcellus** [comment]
That did it, thanks!
