### ISSUE TITLE
Incomplete list of dwarves

### ISSUE THREAD

**Issue by didmar** [splintermind/Dwarf-Therapist#229]
When I refresh the list of dwarves in DT while DF is running, I get a (different) partial list each time.
I'm using DF 0.40.20 and DT commit aa744bd060 on Linux

**Comment by splintermind** [comment]
This is due to some changes in the [invalid_flags] section, at the very least the zombie flag check has changed.

To work around it until layouts are updated, you can replace the `[invalid_flags_1]` section with this:

```
[invalid_flags_1]
size=9
1\name=a skeleton
1\value=0x00002000
2\name=a merchant
2\value=0x00000040
3\name=outpost liason or diplomat
3\value=0x00000800
4\name=an invader or hostile
4\value=0x00020000
5\name=an invader or hostile
5\value=0x00080000
6\name=resident, invader or ambusher
6\value=0x00600000
7\name=part of a merchant caravan
7\value=0x00000080
8\name="Dead, Jim."
8\value=0x00000002
9\name=marauder
9\value=0x00000010
```

I don't know if there are other altered flags and I don't know if zombies will still be excluded from DT since it also checks for dead and opposed to life.

**Comment by didmar** [comment]
ok, I just had to replace the [invalid_flags_1] section in share/memory_layouts/linux/v040.20.in like you suggested, it works now. Thanks !
