### ISSUE TITLE
Match Happiness categories with ingame

### ISSUE THREAD

**Issue by kwaio** [splintermind/Dwarf-Therapist#252]
In 0.40, happiness has been changed to stress levels.
That being said, Dwarf therapist sorts dwarves in "Fine" (-inf to 100k stress), Unhappy(100-200k?) or Very unhappy, (200/250k+ including "Insane" status)

I think that it should either stick to the old classification (http://dwarffortresswiki.org/index.php/v0.34:Thought#The_mechanics_of_thoughts) which DFhack displays on the bottom right conveniently, or choose a color gradient more helpful.

Having the same color/category for a -50k stress dwarf and 100k is misleading.

DFhack's scale is : 
-inf -> 0 / 0-30k / 30k-60k / 60k - 100k / 100k-250k / 250k-500k / 500k+

**Comment by splintermind** [comment]
The current happiness ranges match the exact ranges in DF. As far as DF is concerned, -100k to 100k in DF is 'Fine'.

I don't see how the dfhack scaling is correct since, for example just having stress < 0 is not ecstatic. That occurs after -500k, iirc.

Anyway, until there's some indication that the currently ranges in DT don't match DF, I don't plan on changing it.

**Comment by lethosor** [comment]
@kwaio you linked to the 0.34 page, by the way.

**Comment by kwaio** [comment]
That was definitly on purpose. I believe a 100k stress dwarf is totally not as "fine" as a -30k one, but as splintermind said, that's how DF consider them.

**Comment by lethosor** [comment]
I assume you're replying to my comment - I was on mobile and didn't realize that you were actually talking about the older version due to wrapping. Sorry about that.
