### ISSUE TITLE
No binaries provided for Linux

### ISSUE THREAD

**Issue by benjamin-kirkbride** [splintermind/Dwarf-Therapist#304]
There are detailed build instructions, but that is really no excuse to not provide pre-built binaries for at least the Debian-based distros. There are almost a gig of dependencies required. On a slower Internet connection, this can mean over an hour of downloading before you can even build. For a program that is only a couple dozen megabytes, this seems absurd.

Is it a lack of man-power? Something technical? Ideological? I can't believe that somehow mapping all the memory for Linux is less work than actually providing a reasonable installation method.

**Comment by lethosor** [comment]
int_ua has put some up on DFFD, like http://dffd.bay12games.com/file.php?id=9900 (I couldn't find one for 0.42.06 though)

The real problem here is that splintermind only hosts Windows binaries in this repo. Other people build for other platforms, but those builds don't end up here for some reason.

**Comment by benjamin-kirkbride** [comment]
I am aware that there are unofficial builds that can be found floating around, but that isn't exactly safe, nor convenient.

**Comment by benjamin-kirkbride** [comment]
It just seems unreasonable to me that installing wine and running therapist through that is orders of magnitude more convenient than installing it natively.

**Comment by noirscape** [comment]
Withing regards to this, creating a linux binary (at least for debian and by extension ubuntu) is very easy. Run `sudo checkinstall` after finishing a build instead of `sudo make install` and you will receive a deb. You can then install said deb by running `sudo dpkg -i GENERATEDDEB.deb` (take a guess what should be replaced here). You can change the maintainer and depends fields during `checkinstall`s generation.

I've attached a sample version of a deb generated by `checkinstall` below.  Note that it doesn't include the proper depends or maintainer fields, as I was recompiling it to source.changes for a PPA and added my own debian directory and control file.

[dt.zip](https://github.com/splintermind/Dwarf-Therapist/files/264972/dt.zip)

**Comment by TC01** [comment]
I've also started making Fedora packages for Dwarf Therapist. Until I manage to get them into, say,  [RPM Fusion](http://rpmfusion.org), I'm providing a [repository](https://www.acm.jhu.edu/~bjr/fedora/dwarffortress/dwarffortress.repo) for anyone who wants to use them. (On Fedora 23 or Fedora 24, you can simply copy that file into `/etc/yum.repos.d` and run `sudo dnf install dwarftherapist`). I made the package using [this RPM spec file](https://www.acm.jhu.edu/~bjr/fedora/dwarffortress/rpmfusion/dwarftherapist.spec).

**Comment by probonopd** [comment]
Why not do a cross-distro [AppImage](http://appimage.org/)? [Many applications](https://github.com/probonopd/AppImageKit/wiki/AppImages) are already distributed this way.

For Qt based applications, you might want to try [linuxdeployqt](https://github.com/probonopd/linuxdeployqt) which pretty much automates the process of packaging an application. It takes an application as input and makes it self-contained by copying in the Qt libraries and plugins that the application uses into a bundle. This can optionally be put into an AppImage.

**Comment by benjamin-kirkbride** [comment]
I just want to say for posterity that the way I wrote in this was extremely entitled. I apologize to @splintermind for that.

**Comment by lethosor** [comment]
In case you haven't seen and are still looking: https://github.com/Dwarf-Therapist/Dwarf-Therapist is a newer fork that does provide a Linux AppImage.
