### ISSUE TITLE
Makefile is still tracked, despite being in .gitignore

### ISSUE THREAD

**Issue by Masken3** [splintermind/Dwarf-Therapist#43]
This causes git to report a change after running "qmake -qt=5".

I encountered it when building DT on Linux.

**Comment by lethosor** [comment]
What's the output of `git status`?

**Comment by Janzert** [comment]
.gitignore only applies to currently untracked files. Since Makefile and Makefile_Linux are being tracked in the repo any changes to them will be picked up.

The line "Makefile*", used in .gitignore in the most recent superlabor branch, will stop any other Makefile_blah files from being noticed unless explicitly added though.

**Comment by Masken3** [comment]
```
:~/code/Dwarf-Therapist$ git status
# On branch DF2014
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#   modified:   Makefile
#
no changes added to commit (use "git add" and/or "git commit -a")
```

I worked around it by running `git update-index --assume-unchanged Makefile`

**Comment by Hello71** [comment]
`git rm Makefile`
